version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  webserver:
    build: ./app
    image: swebber/app
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
